### ISSUE TITLE
Better documentation and an install script

### ISSUE THREAD

**Issue by Jetas18** [ImpossibleReality/Siffra#10]
Basically make a script so that you dont have to figure out too much stuff like installing bun and then tauri private key. A bit of fuss. But with a install script it will be much more easier! So basically a script can be implemented in bash to check if rust is installed if not then install it. same with bun. And all the bun install stuff is good but not too user friendly so you can make the script move the binary file to either local or global PATH. I can help with bash scripting if needed :DD Will try to make a PR soon if I manage to do it

**Comment by ImpossibleReality** [comment]
Tauri private key will not be provided as that is only needed for the autoupdater through github releases, and not needed for development/building binaries.

Also you only need to install two things which I don't think is enough to warrant a whole install script. If you want prebuilt binaries there are some one the [releases page](https://github.com/ImpossibleReality/Siffra/releases/latest). I do agree however, that the project is lacking documentation when it comes to development, and I will begin to work on that as soon as I start accepting more contributions.
