### ISSUE TITLE
UI input offset (windows)

### ISSUE THREAD

**Issue by romancitodev** [ImpossibleReality/Siffra#13]
**Describe the bug**
When I press some enter to create spaces between expressions, the input doesn't align with the text

**To Reproduce**
1. Open Siffra.
2. Make some calcs.
3. Press 2 enters
4. Write anything.

**Expected behavior**
the input is expected to be aligned with the text.

**Screenshots**
![image](https://github.com/ImpossibleReality/Siffra/assets/84428770/6665d4b2-5207-41de-af51-118975312f66)

**Desktop (please complete the following information):**
 - OS: Windows NT
 - Version 0.2.2

**Additional context**
_None_

**Comment by dre-bk201** [comment]
The pull request I submitted to fix this issue was incomplete, will have the issue fixed later today.

**Comment by ImpossibleReality** [comment]
Closed by #14
