### ISSUE TITLE
update loop

### ISSUE THREAD

**Issue by Waradu** [ImpossibleReality/Siffra#7]
![image](https://github.com/ImpossibleReality/Siffra/assets/89935135/2d34aa46-ceb7-4e73-a6a3-5398506c00ec)
this pops up - click update - window closes - again

**Comment by ImpossibleReality** [comment]
I tested this on Windows and I cannot repro. This would also probably not be something that I could fix anyways and would be an upstream issue in the Tauri updater. Closing this, but let me know if the issue persists.
